name: Test Master Branch
on:
  push:
    branches:
      - main

jobs:
  UnitTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO }}

      - name: unittests
        run: go test -race -cover -coverprofile=coverage.out -covermode=atomic -cpu 1,2 -bench . -benchmem ./... > test.log
      - name: Show log
        if: always()
        run: cat test.log

      - name: Codecov
        uses: codecov/codecov-action@v1.5.2
        with:
          file: ./coverage.out

      - name: Mongo
        run: >-
          go run . mongo
          --connection-url="mongodb://${{ secrets.MONGO_USER }}:${{ secrets.MONGO_PASSWORD }}@bench-shard-00-00-jhj17.mongodb.net:27017,bench-shard-00-01-jhj17.mongodb.net:27017,bench-shard-00-02-jhj17.mongodb.net:27017/test?ssl=true&replicaSet=bench-shard-0&authSource=admin&retryWrites=true&w=majority"
          --database="sv-go-tools"
          --collection="grade"
          --tag "hardwareID=github/actions"
          --tag "goVersion=$(go version | cut -d' ' -f3-)"
          --tag "revision=${{ github.sha }}"
          < test.log
